/**
 * 南京旅行攻略 - Mock 数据
 * 包含 16 个南京知名景点的详细数据
 */

// 生成彩色占位 SVG 图片（无需外部图片资源）
function img(label, hue) {
  const c = `hsl(${hue}, 55%, 45%)`
  const c2 = `hsl(${hue}, 50%, 35%)`
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 300">
    <defs><linearGradient id="g"><stop offset="0%" stop-color="${c}"/><stop offset="100%" stop-color="${c2}"/></linearGradient></defs>
    <rect width="400" height="300" fill="url(#g)"/>
    <text x="200" y="140" text-anchor="middle" fill="rgba(255,255,255,0.9)" font-size="20" font-weight="bold" font-family="sans-serif">${label}</text>
    <text x="200" y="175" text-anchor="middle" fill="rgba(255,255,255,0.6)" font-size="14" font-family="sans-serif">📍 Nanjing</text>
  </svg>`
  return `data:image/svg+xml;base64,${btoa(unescape(encodeURIComponent(svg)))}`
}

const spots = [
  {
    id: 1,
    name: '夫子庙-秦淮河',
    alias: 'Confucius Temple & Qinhuai River',
    category: '历史人文',
    district: '秦淮区',
    rating: 4.8,
    ratingCount: 23500,
    coverImage: img('夫子庙-秦淮河', 0),
    images: [img('夫子庙夜景', 0), img('秦淮游船', 15), img('江南贡院', 30)],
    description: '夫子庙-秦淮河风光带是南京最负盛名的文化地标，以孔庙建筑群和秦淮河夜景为核心。这里承载着六朝古都的千年文脉，"烟笼寒水月笼沙，夜泊秦淮近酒家"的诗意画卷在此展开。',
    history: '夫子庙始建于东晋成帝咸康三年（337年），是供奉和祭祀孔子的地方。南宋绍兴年间重建，历代屡毁屡建。秦淮河是南京的母亲河，自古便是金陵繁华之地，六朝时已是名门望族聚居之处。',
    openingHours: '夫子庙：08:30–22:00；秦淮河游船：09:00–21:00',
    ticketPrice: '夫子庙免费，展览馆 ¥30；秦淮河游船 ¥80–¥140',
    suggestedDuration: '3–4 小时',
    bestSeason: '四季皆宜（元宵灯会期间最佳）',
    subway: '地铁 3 号线夫子庙站（2号口出）',
    bus: '1路 / 2路 / 202路 / 44路 / 游4路',
    address: '南京市秦淮区贡院西街',
    latitude: 32.0205,
    longitude: 118.7871,
    tags: ['地标', '夜景', '美食', '游船', '历史文化'],
    popularity: 9800,
    isRecommended: true
  },
  {
    id: 2,
    name: '中山陵',
    alias: 'Sun Yat-sen Mausoleum',
    category: '历史人文',
    district: '玄武区',
    rating: 4.7,
    ratingCount: 18900,
    coverImage: img('中山陵', 210),
    images: [img('中山陵祭堂', 210), img('陵园大道', 200), img('音乐台', 190)],
    description: '中山陵是中国近代民主革命先行者孙中山先生的陵寝，位于紫金山南麓。整个建筑群沿中轴线依山而建，从牌坊到祭堂共392级台阶，气势恢宏，被誉为"中国近代建筑史上第一陵"。',
    history: '中山陵于1926年动工，1929年建成。由著名建筑师吕彦直设计，融合了中国传统建筑风格与西方现代建筑理念，是中国近代建筑史上的经典之作。',
    openingHours: '08:00–17:00（周一闭馆）',
    ticketPrice: '免费（需提前预约）',
    suggestedDuration: '2–3 小时',
    bestSeason: '春季（梅花盛开时尤佳）',
    subway: '地铁 2 号线苜蓿园站（1号口出）',
    bus: '游1路 / 游2路 / 20路 / 315路',
    address: '南京市玄武区紫金山南麓',
    latitude: 32.0642,
    longitude: 118.8493,
    tags: ['地标', '历史', '建筑', '爬山'],
    popularity: 9200,
    isRecommended: true
  },
  {
    id: 3,
    name: '明孝陵',
    alias: 'Ming Xiaoling Mausoleum',
    category: '历史人文',
    district: '玄武区',
    rating: 4.6,
    ratingCount: 15600,
    coverImage: img('明孝陵', 350),
    images: [img('神道石象', 350), img('明楼', 340), img('梅花山', 330)],
    description: '明孝陵是明朝开国皇帝朱元璋与马皇后的合葬陵墓，位于紫金山独龙阜。它是中国规模最大的帝王陵寝之一，其神道石刻被誉为"南京最美600米"。',
    history: '明孝陵始建于1381年，历时25年建成。其"前朝后寝"的陵寝格局为明清两代帝王陵寝制度奠定了基础，2003年被列入世界文化遗产。',
    openingHours: '06:30–18:00（夏令时）/ 07:00–17:30（冬令时）',
    ticketPrice: '¥60（不含梅花山）',
    suggestedDuration: '2–3 小时',
    bestSeason: '秋季（神道银杏金黄）',
    subway: '地铁 2 号线苜蓿园站（1号口出）',
    bus: '游1路 / 游2路 / 315路',
    address: '南京市玄武区紫金山南麓独龙阜玩珠峰下',
    latitude: 32.0529,
    longitude: 118.8354,
    tags: ['世界遗产', '历史', '石刻', '赏秋'],
    popularity: 8800,
    isRecommended: true
  },
  {
    id: 4,
    name: '南京博物院',
    alias: 'Nanjing Museum',
    category: '博物馆',
    district: '玄武区',
    rating: 4.7,
    ratingCount: 17200,
    coverImage: img('南京博物院', 280),
    images: [img('历史馆', 280), img('特展馆', 270), img('民国馆', 260)],
    description: '南京博物院是中国三大博物馆之一，前身为国立中央博物院。馆藏文物超过43万件，从史前文明到明清珍品，涵盖中华文明发展的各个阶段。',
    history: '南京博物院于1936年由蔡元培等人倡议筹建，1948年建成开放。建筑仿辽代风格，气势宏伟。现设有历史馆、特展馆、数字馆、艺术馆、非遗馆和民国馆六大展馆。',
    openingHours: '09:00–17:00（周一闭馆）',
    ticketPrice: '免费（需提前预约）',
    suggestedDuration: '3–4 小时',
    bestSeason: '四季皆宜',
    subway: '地铁 2 号线明故宫站（1号口出）',
    bus: '5路 / 9路 / 34路 / 游1路 / 游2路',
    address: '南京市玄武区中山东路321号',
    latitude: 32.0426,
    longitude: 118.8269,
    tags: ['博物馆', '文化', '历史', '免费'],
    popularity: 9000,
    isRecommended: true
  },
  {
    id: 5,
    name: '总统府',
    alias: 'Presidential Palace',
    category: '历史人文',
    district: '玄武区',
    rating: 4.5,
    ratingCount: 14300,
    coverImage: img('总统府', 30),
    images: [img('总统府大门', 30), img('煦园', 20), img('办公楼', 10)],
    description: '南京总统府是中国近代史的重要见证，曾是太平天国天王府、两江总督署、中华民国总统府所在地。中国一系列重大历史事件在此发生。',
    history: '总统府建筑群始于明朝汉王府，清代为两江总督署。1853年太平天国定都南京后改为天王府。1912年中华民国临时政府在此成立，此后一直是政治中枢。1949年解放军占领总统府标志国民党统治覆灭。',
    openingHours: '08:30–18:00（夏令时）/ 08:30–17:00（冬令时，周一闭馆）',
    ticketPrice: '¥35',
    suggestedDuration: '2–3 小时',
    bestSeason: '四季皆宜',
    subway: '地铁 2 / 3 号线大行宫站（5号口出）',
    bus: '1路 / 5路 / 9路 / 25路 / 31路 / 游1路 / 游2路',
    address: '南京市玄武区长江路292号',
    latitude: 32.0414,
    longitude: 118.7921,
    tags: ['历史', '建筑', '近代史', '地标'],
    popularity: 8500,
    isRecommended: false
  },
  {
    id: 6,
    name: '玄武湖',
    alias: 'Xuanwu Lake',
    category: '自然风光',
    district: '玄武区',
    rating: 4.6,
    ratingCount: 16800,
    coverImage: img('玄武湖', 190),
    images: [img('玄武湖全景', 190), img('樱洲', 180), img('台城', 170)],
    description: '玄武湖是江南最大的城内公园，被誉为"金陵明珠"。湖中有五洲（环洲、樱洲、菱洲、梁洲、翠洲），洲洲有桥相连。东枕紫金山，西依明城墙，景色秀丽。',
    history: '玄武湖古称桑泊，六朝时为皇家园林湖泊。明代以玄武湖为禁地，储藏天下黄册（户籍档案）。1911年辟为公园对外开放，是南京市民最喜爱的休闲去处。',
    openingHours: '06:00–21:00（环湖路全天开放）',
    ticketPrice: '免费',
    suggestedDuration: '2–3 小时',
    bestSeason: '春季（樱花盛开） / 夏季（荷花满塘）',
    subway: '地铁 1 号线玄武门站（3号口出）',
    bus: '1路 / 3路 / 8路 / 15路 / 22路 / 25路 / 28路',
    address: '南京市玄武区玄武巷1号',
    latitude: 32.0702,
    longitude: 118.7880,
    tags: ['公园', '湖泊', '休闲', '赏花', '免费'],
    popularity: 9100,
    isRecommended: true
  },
  {
    id: 7,
    name: '鸡鸣寺',
    alias: 'Jiming Temple',
    category: '宗教寺庙',
    district: '玄武区',
    rating: 4.5,
    ratingCount: 12100,
    coverImage: img('鸡鸣寺', 320),
    images: [img('鸡鸣寺春色', 320), img('药师塔', 310), img('樱花大道', 300)],
    description: '鸡鸣寺是南京最古老的梵刹之一，始建于西晋，有"南朝第一寺"之称。寺前樱花大道是南京春季最著名的赏樱胜地，每年三月吸引无数游客。',
    history: '鸡鸣寺始建于西晋永康元年（300年），是金陵最古老的寺庙之一。唐代诗人杜牧诗句"南朝四百八十寺，多少楼台烟雨中"即描绘了以鸡鸣寺为代表的南朝佛教盛况。',
    openingHours: '07:00–17:00',
    ticketPrice: '¥10',
    suggestedDuration: '1–1.5 小时',
    bestSeason: '春季（樱花季）',
    subway: '地铁 3 / 4 号线鸡鸣寺站（5号口出）',
    bus: '11路 / 20路 / 48路 / 67路',
    address: '南京市玄武区鸡鸣寺路1号',
    latitude: 32.0591,
    longitude: 118.7882,
    tags: ['寺庙', '樱花', '历史', '祈福'],
    popularity: 8200,
    isRecommended: true
  },
  {
    id: 8,
    name: '老门东',
    alias: 'Laomendong',
    category: '历史人文',
    district: '秦淮区',
    rating: 4.4,
    ratingCount: 9800,
    coverImage: img('老门东', 40),
    images: [img('老门东街巷', 40), img('城墙夜景', 35), img('金陵刻经处', 30)],
    description: '老门东是南京保存最完好的历史街区之一，因位于中华门以东而得名。青砖黛瓦、石板小巷，集中展示了南京明清时期的民居建筑风格和市井生活。',
    history: '老门东一带早在三国时期就是繁华的居民区，明清时期更是商贾云集。如今经过修缮保护，成为集历史文化、美食购物、艺术创意于一体的综合街区。',
    openingHours: '全天开放',
    ticketPrice: '免费',
    suggestedDuration: '2–3 小时',
    bestSeason: '四季皆宜',
    subway: '地铁 3 号线武定门站（2号口出）',
    bus: '14路 / 23路 / 43路 / 46路 / 87路 / 301路',
    address: '南京市秦淮区剪子巷',
    latitude: 32.0121,
    longitude: 118.7924,
    tags: ['历史街区', '美食', '文艺', '拍照', '免费'],
    popularity: 7800,
    isRecommended: false
  },
  {
    id: 9,
    name: '紫金山',
    alias: 'Purple Mountain',
    category: '自然风光',
    district: '玄武区',
    rating: 4.7,
    ratingCount: 14500,
    coverImage: img('紫金山', 250),
    images: [img('紫金山日出', 250), img('头陀岭', 240), img('紫金山天文台', 230)],
    description: '紫金山又名钟山，是南京的"城市绿肺"，主峰海拔448.9米。山上有中山陵、明孝陵、灵谷寺等众多名胜，山脚下的梧桐大道是南京最美道路之一。',
    history: '紫金山自古就是金陵名胜，六朝时为皇家苑囿。山上有三国时孙权陵墓、明代紫金山天文台（中国最早的现代天文台）等众多历史遗迹。',
    openingHours: '全天开放',
    ticketPrice: '免费（部分景点单独收费）',
    suggestedDuration: '半天至一天',
    bestSeason: '四季皆宜（秋日红叶最佳）',
    subway: '地铁 4 号线蒋王庙站（登山口）',
    bus: '20路 / 48路 / 67路 / 315路 / 游3路',
    address: '南京市玄武区紫金山',
    latitude: 32.0687,
    longitude: 118.8332,
    tags: ['登山', '自然', '观景', '徒步', '免费'],
    popularity: 8600,
    isRecommended: false
  },
  {
    id: 10,
    name: '侵华日军南京大屠杀遇难同胞纪念馆',
    alias: 'Memorial Hall of Victims in Nanjing Massacre',
    category: '历史人文',
    district: '建邺区',
    rating: 4.9,
    ratingCount: 21000,
    coverImage: img('南京大屠杀纪念馆', 0),
    images: [img('纪念馆外景', 0), img('万人坑遗址', 350), img('和平钟', 340)],
    description: '纪念馆是铭记1937年南京大屠杀历史的重要场所，展示了大量珍贵的历史资料和实物。建筑由著名建筑师何镜堂设计，整体色调灰暗庄重，让人肃然起敬。',
    history: '纪念馆于1985年建成开放，2005年扩建。馆址位于侵华日军南京大屠杀江东门集体屠杀遗址和遇难者丛葬地。现为全国爱国主义教育示范基地。',
    openingHours: '08:30–16:30（周一闭馆）',
    ticketPrice: '免费（需提前预约）',
    suggestedDuration: '2–3 小时',
    bestSeason: '四季皆宜',
    subway: '地铁 2 号线云锦路站（2号口出）',
    bus: '7路 / 37路 / 61路 / 63路 / 166路',
    address: '南京市建邺区水西门大街418号',
    latitude: 32.0387,
    longitude: 118.7484,
    tags: ['纪念馆', '历史教育', '免费', '必去'],
    popularity: 9500,
    isRecommended: true
  },
  {
    id: 11,
    name: '阅江楼',
    alias: 'Yuejiang Tower',
    category: '历史人文',
    district: '鼓楼区',
    rating: 4.3,
    ratingCount: 7800,
    coverImage: img('阅江楼', 50),
    images: [img('阅江楼全景', 50), img('长江远眺', 40), img('楼内陈设', 30)],
    description: '阅江楼位于狮子山巅，与武汉黄鹤楼、岳阳岳阳楼、南昌滕王阁并称"江南四大名楼"。登楼远眺，万里长江尽收眼底，气势磅礴。',
    history: '阅江楼始建于明朝洪武年间，因明太祖朱元璋曾在此阅兵而得名。后屡毁屡建，2001年重建开放。楼内陈列有郑和下西洋相关文物。',
    openingHours: '08:00–17:30',
    ticketPrice: '¥40',
    suggestedDuration: '1.5–2 小时',
    bestSeason: '秋季（天高气爽，视野最佳）',
    subway: '地铁 1 号线迈皋桥站转公交',
    bus: '10路 / 12路 / 16路 / 21路 / 39路',
    address: '南京市鼓楼区建宁路202号',
    latitude: 32.1041,
    longitude: 118.7525,
    tags: ['名楼', '长江', '历史', '登高'],
    popularity: 6500,
    isRecommended: false
  },
  {
    id: 12,
    name: '栖霞山',
    alias: 'Qixia Mountain',
    category: '自然风光',
    district: '栖霞区',
    rating: 4.6,
    ratingCount: 13200,
    coverImage: img('栖霞山', 10),
    images: [img('栖霞红叶', 10), img('栖霞寺', 0), img('千佛岩', 350)],
    description: '栖霞山被誉为"金陵第一明秀山"，以秋季红叶闻名天下。山中有千年古刹栖霞寺，以及千佛岩、舍利塔等众多佛教文化遗迹。',
    history: '栖霞寺始建于南齐永明元年（483年），是中国佛教三论宗的发源地。千佛岩开凿于南齐至明代，共有佛龛294座、佛像515尊，有"东敦煌"之称。',
    openingHours: '07:00–17:00',
    ticketPrice: '¥20（红叶季 ¥40）',
    suggestedDuration: '3–4 小时',
    bestSeason: '秋季（10月下旬–12月初红叶最佳）',
    subway: '地铁 2 号线南大仙林站转公交',
    bus: '138路 / 194路 / 195路 / 196路 / 206路',
    address: '南京市栖霞区栖霞街88号',
    latitude: 32.1275,
    longitude: 118.9620,
    tags: ['红叶', '登山', '寺庙', '赏秋', '佛教'],
    popularity: 8000,
    isRecommended: true
  },
  {
    id: 13,
    name: '灵谷寺',
    alias: 'Linggu Temple',
    category: '宗教寺庙',
    district: '玄武区',
    rating: 4.4,
    ratingCount: 7600,
    coverImage: img('灵谷寺', 130),
    images: [img('无梁殿', 130), img('灵谷塔', 120), img('灵谷深松', 110)],
    description: '灵谷寺位于紫金山东南坡，是明代三大佛教寺院之一。寺内无梁殿全部以砖石砌成，不施寸木，是中国古代建筑史上的奇迹。',
    history: '灵谷寺始建于南朝梁代，原址在紫金山南麓独龙阜，明洪武十四年（1381年）为修建明孝陵而迁至今址。康熙、乾隆南巡时均曾驾临。',
    openingHours: '08:00–17:00',
    ticketPrice: '¥35（含在钟山风景区联票内）',
    suggestedDuration: '1.5–2 小时',
    bestSeason: '夏季（灵谷深松，清凉避暑）',
    subway: '地铁 2 号线苜蓿园站转景区接驳车',
    bus: '游2路 / 游3路 / 202路',
    address: '南京市玄武区紫金山东南坡',
    latitude: 32.0467,
    longitude: 118.8687,
    tags: ['寺庙', '古建筑', '历史', '清幽'],
    popularity: 6200,
    isRecommended: false
  },
  {
    id: 14,
    name: '雨花台',
    alias: 'Yuhuatai',
    category: '历史人文',
    district: '雨花台区',
    rating: 4.3,
    ratingCount: 8900,
    coverImage: img('雨花台', 270),
    images: [img('雨花台烈士群雕', 270), img('雨花石', 260), img('忠魂亭', 250)],
    description: '雨花台是一座以烈士陵园为核心的纪念性景区，也是南京著名的风景名胜。这里盛产雨花石，色彩斑斓、纹理奇特，深受收藏爱好者喜爱。',
    history: '雨花台因盛产五彩雨花石而得名。1927年至1949年间，这里成为国民党屠杀共产党人和爱国志士的刑场。新中国成立后在此建立烈士陵园，是全国最大的烈士陵园之一。',
    openingHours: '08:00–17:00',
    ticketPrice: '免费',
    suggestedDuration: '2–3 小时',
    bestSeason: '四季皆宜',
    subway: '地铁 1 号线中华门站（3号口出）',
    bus: '2路 / 16路 / 26路 / 33路 / 88路 / 94路',
    address: '南京市雨花台区雨花路215号',
    latitude: 32.0012,
    longitude: 118.7777,
    tags: ['红色旅游', '烈士陵园', '雨花石', '免费'],
    popularity: 7000,
    isRecommended: false
  },
  {
    id: 15,
    name: '朝天宫',
    alias: 'Chaotian Palace',
    category: '历史人文',
    district: '秦淮区',
    rating: 4.2,
    ratingCount: 6100,
    coverImage: img('朝天宫', 40),
    images: [img('朝天宫牌坊', 40), img('大成殿', 35), img('敬一亭', 30)],
    description: '朝天宫是江南地区保存最完整的明清官式古建筑群，现为南京市博物馆所在地。整体建筑依山而建，气势恢宏，红墙碧瓦，极具皇家气派。',
    history: '朝天宫始建于明洪武年间，是朱元璋为朝拜天子而建。清康熙、乾隆南巡时均曾到此。太平天国时期被毁，同治年间重建。现为全国重点文物保护单位。',
    openingHours: '09:00–17:00（周一闭馆）',
    ticketPrice: '¥25',
    suggestedDuration: '1.5–2 小时',
    bestSeason: '四季皆宜',
    subway: '地铁 1 号线张府园站（3号口出）',
    bus: '4路 / 23路 / 43路 / 48路 / 83路',
    address: '南京市秦淮区朝天宫路6号',
    latitude: 32.0318,
    longitude: 118.7805,
    tags: ['古建筑', '博物馆', '历史', '明代'],
    popularity: 5500,
    isRecommended: false
  },
  {
    id: 16,
    name: '牛首山',
    alias: 'Niushou Mountain',
    category: '宗教寺庙',
    district: '江宁区',
    rating: 4.5,
    ratingCount: 11400,
    coverImage: img('牛首山', 290),
    images: [img('佛顶宫', 290), img('佛顶塔', 280), img('禅境大观', 270)],
    description: '牛首山因东西双峰形似牛头而得名，是佛教牛头禅宗的发源地。山上的佛顶宫供奉有释迦牟尼佛顶骨舍利，建筑融合了传统佛教艺术与现代设计，极为壮观。',
    history: '牛首山自古就是佛教圣地，唐代法融禅师在此创立牛头宗。2015年，佛顶宫建成开放，供奉佛顶骨舍利，成为世界佛教文化新地标。',
    openingHours: '08:30–17:00',
    ticketPrice: '¥80',
    suggestedDuration: '3–4 小时',
    bestSeason: '春季（山花烂漫） / 秋季',
    subway: '地铁 S3 号线春江路站转公交',
    bus: '755路 / 710路 / 853路',
    address: '南京市江宁区牛首山文化旅游区',
    latitude: 31.9056,
    longitude: 118.7564,
    tags: ['佛教', '舍利', '建筑', '文化'],
    popularity: 8400,
    isRecommended: true
  }
]

const tips = {
  bestSeason: {
    title: '最佳旅行季节',
    description: '南京四季分明，各有韵味。春季（3–5月）是最佳旅行季节，樱花、梅花、海棠竞相开放，气温宜人。秋季（9–11月）天高气爽，栖霞山红叶如火，同样非常适合旅行。夏季炎热潮湿，冬季湿冷，但游客较少，适合喜欢安静的旅行者。',
    seasons: [
      { name: '春季（3–5月）', weather: '15–25°C', highlights: '樱花、梅花、海棠', rating: '⭐⭐⭐⭐⭐' },
      { name: '夏季（6–8月）', weather: '25–38°C', highlights: '玄武湖荷花、灵谷避暑', rating: '⭐⭐⭐' },
      { name: '秋季（9–11月）', weather: '10–25°C', highlights: '栖霞红叶、明孝陵神道', rating: '⭐⭐⭐⭐⭐' },
      { name: '冬季（12–2月）', weather: '0–10°C', highlights: '雪景、腊梅、温泉', rating: '⭐⭐⭐⭐' }
    ]
  },
  routes: [
    {
      title: '一日游精华',
      duration: '1 天',
      schedule: [
        '上午：中山陵 → 明孝陵神道',
        '中午：夫子庙吃小吃',
        '下午：南京博物院 → 总统府',
        '晚上：夫子庙秦淮河夜景 + 游船'
      ],
      tip: '行程较紧，建议早出晚归。购买钟山风景区联票更划算。'
    },
    {
      title: '两日游经典',
      duration: '2 天',
      schedule: [
        '第一天：中山陵 → 明孝陵 → 灵谷寺 → 玄武湖',
        '第二天：南京博物院 → 总统府 → 老门东午餐 → 夫子庙 → 秦淮河夜景'
      ],
      tip: '第一天体力消耗较大，建议穿舒适徒步鞋。'
    },
    {
      title: '三日游深度',
      duration: '3 天',
      schedule: [
        '第一天：中山陵 → 明孝陵 → 灵谷寺 → 紫金山徒步',
        '第二天：南京博物院 → 总统府 → 鸡鸣寺 → 玄武湖',
        '第三天：大屠杀纪念馆 → 老门东午餐 → 夫子庙 → 秦淮河游船'
      ],
      tip: '第三天下午行程较轻松，可灵活调整。纪念馆需提前预约。'
    }
  ],
  foods: [
    { name: '鸭血粉丝汤', description: '南京最出名的小吃，粉丝配上鸭血、鸭肠、豆腐泡，汤鲜味美。', place: '回味鸭血粉丝（连锁店）' },
    { name: '盐水鸭', description: '南京人的"无鸭不成席"，皮白肉嫩，咸香入味。', place: '韩复兴（夫子庙店）' },
    { name: '小笼包', description: '皮薄馅大汁多，咬开先吸汤再吃馅。', place: '鸡鸣酒家 / 尹氏汤包' },
    { name: '鸭油烧饼', description: '用鸭油和面的酥皮烧饼，香气独特，酥脆可口。', place: '老门东小郑酥烧饼' },
    { name: '梅花糕', description: '形似梅花的传统糕点，外酥内软，豆沙馅甜而不腻。', place: '夫子庙 / 老门东街头' },
    { name: '糖芋苗', description: '南京传统甜品，芋苗软糯，桂花糖浆香甜。', place: '蓝老大糖粥藕店' }
  ],
  accommodations: [
    { district: '秦淮区（夫子庙/老门东）', description: '南京最热门住宿区域，紧邻夫子庙秦淮河，夜景绝佳。适合初次来南京的游客。', price: '¥200–¥800/晚' },
    { district: '玄武区（新街口/鼓楼）', description: '市中心商业区，交通便利，地铁枢纽。适合商务出行和购物爱好者。', price: '¥250–¥1000/晚' },
    { district: '江宁区（百家湖/九龙湖）', description: '新兴商圈，酒店性价比高。距离牛首山较近，适合自驾游客。', price: '¥150–¥600/晚' },
    { district: '栖霞区（仙林）', description: '大学城区域，安静宜居。适合去栖霞山游玩的游客。', price: '¥150–¥500/晚' }
  ]
}

// 景点区域列表
const districts = [
  { name: '秦淮区', count: 4 },
  { name: '玄武区', count: 6 },
  { name: '鼓楼区', count: 1 },
  { name: '建邺区', count: 1 },
  { name: '栖霞区', count: 1 },
  { name: '雨花台区', count: 1 },
  { name: '江宁区', count: 1 }
]

export { spots, tips, districts }
